{
 "title": "Resilience",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Rate Limiter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_ratelimiter_available_permissions",
     "legendFormat": "Permissions {{name}}"
    },
    {
     "expr": "resilience4j_ratelimiter_waiting_threads",
     "legendFormat": "Threads {{name}}"
    }
   ]
  },
  { "title": "Retry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Retry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_retry_calls{application=\"resilience4j-demo\"}",
     "legendFormat": "{{name}} - {{kind}}"
    }
   ]
  },
  { "title": "Circuit breaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Circuit breaker state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{application=\"resilience4j-demo\"}",
     "legendFormat": "{{name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Failure rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{application=\"resilience4j-demo\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Bulkhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Bulhead - Available concurrent calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_bulkhead_available_concurrent_calls{application=\"resilience4j-demo\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}