version: '3'
services:
  resilience4j-demo:
    ports:
      - 8080:8080
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
  prometheus:
    ports:
      - 9090:9090
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    env_file:
      - ./grafana.env
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning
